version: '3.8'
services:
  db:
      container_name: audio_pg
      image: postgres:15
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: postgres
      ports:
      - "5437:5432"
      volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local